name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SECRET_ENV_MODE: ${{ secrets.SECRET_ENV_MODE }}
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Clean Install
        run: npm ci && npx playwright install
      - name: Playright Tests
        run: npm run test
      - name: Unit Tests
        run: npm run test:unit
