name: Merge Dependabot Pull Requests
on:
  pull_request:
    types: [closed]
    branches:
      - updates
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
